### ISSUE TITLE
Download appears intermittent

### ISSUE THREAD

**Issue by josephrbennett** [NCC-CNC/whattodo#34] opened 2022-02-18 16:35 UTC
Download function for solution ceased working during my session, though the app appears to be running fine.

**Comment by jeffreyhanson** [comment] 2022-02-20 20:36
Thank you for catching  this - I'll take a look and see what I can do.

**Comment by jeffreyhanson** [comment] 2022-03-13 19:21
@josephrbennett, I just wanted to follow up and ask if you've been able to reproduce this bug and, if so, what steps are needed to trigger it?

**Comment by jeffreyhanson** [comment] 2022-03-15 01:56
Ok great - thanks for checking again! It's possible that some of other patches to the app might have fixed this bug too.

**Comment by jeffreyhanson** [comment] 2022-03-15 01:57
Since we can't reproduce this issue, I'll close this issue now - but please feel free to re-open if you encounter it again.

**Closed by jeffreyhanson** 2022-03-15 01:57 UTC
Labels: bug, high priority
